### ISSUE TITLE
Phone Numbers Length < 10 allowed

### ISSUE THREAD

**Issue by twh0008** [bpeter97/gbr-mern#3]
Phone number length less than 10 allowed.

**Comment by bpeter97** [comment]
Added additional validation to check to see if incoming phone number is an integer and contains 10 digits.

Here is the result:

> if (validator.isEmpty(data.phone)) {
    errors.phone = "Phone is required.";
  } else if (!(validator.isInt(data.phone) && data.phone.length == 10)) {
    errors.phone =
      "Must contain 10 digits, no dashes or parenthesis. ex: 5591234567";
  }
